replicaCount: 2

image:
  repository: victorazesc/hello-web
  tag: "1.1"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

containerPort: 3000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"