name: CI/CD - hello-web (ECR + EKS)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER: devops-sre-lab
  ECR_REPOSITORY: hello-web
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux, eks]   # labels que você passou no runner (RUNNER_LABELS="eks")
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Em EC2 com Instance Profile, você pode dispensar as keys.
      # Se quiser manter o action, use só a região (ele respeita a credencial da EC2):
      - name: Configure AWS region (use instance profile)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image vars
        id: vars
        run: |
          echo "image_repo=${{ steps.ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}" >> $GITHUB_OUTPUT
          echo "image_full=${{ steps.ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT
          echo "image_latest=${{ steps.ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest" >> $GITHUB_OUTPUT

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push (amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ steps.vars.outputs.image_full }}
            ${{ steps.vars.outputs.image_latest }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.30.0

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Update kubeconfig (dentro da VPC)
        run: aws eks update-kubeconfig --name "${EKS_CLUSTER}" --region "${AWS_REGION}"

      - name: Helm upgrade
        run: |
          helm upgrade --install hello charts/hello-web \
            -n devops-lab --create-namespace \
            --set image.repository="${{ steps.vars.outputs.image_repo }}" \
            --set image.tag="${{ env.IMAGE_TAG }}" \
            --wait --timeout 5m

      - name: Check rollout
        run: kubectl rollout status deploy/hello-hello-web -n devops-lab